/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DoacaoRouteImport } from './routes/doacao'
import { Route as MinisteriosRouteImport } from './routes/ministerios'
import { Route as OndeEstamosRouteImport } from './routes/onde-estamos'
import { Route as RedesRouteImport } from './routes/redes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as VoluntarioRouteImport } from './routes/voluntario'
import { Route as AdminEsqueciSenhaRouteImport } from './routes/admin.esqueci-senha'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminRedefinirSenhaRouteImport } from './routes/admin.redefinir-senha'
import { Route as AgendaIndexRouteImport } from './routes/agenda.index'
import { Route as AgendaSlugRouteImport } from './routes/agenda.$slug'
import { Route as MensagensIndexRouteImport } from './routes/mensagens.index'
import { Route as MensagensSlugRouteImport } from './routes/mensagens.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin.eventos'
import { Route as AuthenticatedAdminFormulariosRouteImport } from './routes/_authenticated/admin.formularios'
import { Route as AuthenticatedAdminMensagensRouteImport } from './routes/_authenticated/admin.mensagens'
import { Route as AuthenticatedAdminPaginasRouteImport } from './routes/_authenticated/admin.paginas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DoacaoRoute = DoacaoRouteImport.update({
  id: '/doacao',
  path: '/doacao',
  getParentRoute: () => rootRouteImport,
} as any)
const MinisteriosRoute = MinisteriosRouteImport.update({
  id: '/ministerios',
  path: '/ministerios',
  getParentRoute: () => rootRouteImport,
} as any)
const OndeEstamosRoute = OndeEstamosRouteImport.update({
  id: '/onde-estamos',
  path: '/onde-estamos',
  getParentRoute: () => rootRouteImport,
} as any)
const RedesRoute = RedesRouteImport.update({
  id: '/redes',
  path: '/redes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const VoluntarioRoute = VoluntarioRouteImport.update({
  id: '/voluntario',
  path: '/voluntario',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEsqueciSenhaRoute = AdminEsqueciSenhaRouteImport.update({
  id: '/admin/esqueci-senha',
  path: '/admin/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRedefinirSenhaRoute = AdminRedefinirSenhaRouteImport.update({
  id: '/admin/redefinir-senha',
  path: '/admin/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaSlugRoute = AgendaSlugRouteImport.update({
  id: '/agenda/$slug',
  path: '/agenda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensIndexRoute = MensagensIndexRouteImport.update({
  id: '/mensagens/',
  path: '/mensagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const MensagensSlugRoute = MensagensSlugRouteImport.update({
  id: '/mensagens/$slug',
  path: '/mensagens/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/admin/configuracoes',
    path: '/admin/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/admin/eventos',
    path: '/admin/eventos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFormulariosRoute =
  AuthenticatedAdminFormulariosRouteImport.update({
    id: '/admin/formularios',
    path: '/admin/formularios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMensagensRoute =
  AuthenticatedAdminMensagensRouteImport.update({
    id: '/admin/mensagens',
    path: '/admin/mensagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaginasRoute =
  AuthenticatedAdminPaginasRouteImport.update({
    id: '/admin/paginas',
    path: '/admin/paginas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/doacao': typeof DoacaoRoute
  '/ministerios': typeof MinisteriosRoute
  '/onde-estamos': typeof OndeEstamosRoute
  '/redes': typeof RedesRoute
  '/sobre': typeof SobreRoute
  '/voluntario': typeof VoluntarioRoute
  '/admin/esqueci-senha': typeof AdminEsqueciSenhaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/redefinir-senha': typeof AdminRedefinirSenhaRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/mensagens/$slug': typeof MensagensSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/agenda/': typeof AgendaIndexRoute
  '/mensagens/': typeof MensagensIndexRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/formularios': typeof AuthenticatedAdminFormulariosRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/paginas': typeof AuthenticatedAdminPaginasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/doacao': typeof DoacaoRoute
  '/ministerios': typeof MinisteriosRoute
  '/onde-estamos': typeof OndeEstamosRoute
  '/redes': typeof RedesRoute
  '/sobre': typeof SobreRoute
  '/voluntario': typeof VoluntarioRoute
  '/admin/esqueci-senha': typeof AdminEsqueciSenhaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/redefinir-senha': typeof AdminRedefinirSenhaRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/mensagens/$slug': typeof MensagensSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/agenda': typeof AgendaIndexRoute
  '/mensagens': typeof MensagensIndexRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/admin/formularios': typeof AuthenticatedAdminFormulariosRoute
  '/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/admin/paginas': typeof AuthenticatedAdminPaginasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/contato': typeof ContatoRoute
  '/doacao': typeof DoacaoRoute
  '/ministerios': typeof MinisteriosRoute
  '/onde-estamos': typeof OndeEstamosRoute
  '/redes': typeof RedesRoute
  '/sobre': typeof SobreRoute
  '/voluntario': typeof VoluntarioRoute
  '/admin/esqueci-senha': typeof AdminEsqueciSenhaRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/redefinir-senha': typeof AdminRedefinirSenhaRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/mensagens/$slug': typeof MensagensSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/agenda/': typeof AgendaIndexRoute
  '/mensagens/': typeof MensagensIndexRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/_authenticated/admin/formularios': typeof AuthenticatedAdminFormulariosRoute
  '/_authenticated/admin/mensagens': typeof AuthenticatedAdminMensagensRoute
  '/_authenticated/admin/paginas': typeof AuthenticatedAdminPaginasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/doacao'
    | '/ministerios'
    | '/onde-estamos'
    | '/redes'
    | '/sobre'
    | '/voluntario'
    | '/admin/esqueci-senha'
    | '/admin/login'
    | '/admin/redefinir-senha'
    | '/agenda/$slug'
    | '/mensagens/$slug'
    | '/p/$slug'
    | '/agenda/'
    | '/mensagens/'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/formularios'
    | '/admin/mensagens'
    | '/admin/paginas'
    | '/admin/usuarios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/doacao'
    | '/ministerios'
    | '/onde-estamos'
    | '/redes'
    | '/sobre'
    | '/voluntario'
    | '/admin/esqueci-senha'
    | '/admin/login'
    | '/admin/redefinir-senha'
    | '/agenda/$slug'
    | '/mensagens/$slug'
    | '/p/$slug'
    | '/agenda'
    | '/mensagens'
    | '/admin/configuracoes'
    | '/admin/eventos'
    | '/admin/formularios'
    | '/admin/mensagens'
    | '/admin/paginas'
    | '/admin/usuarios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contato'
    | '/doacao'
    | '/ministerios'
    | '/onde-estamos'
    | '/redes'
    | '/sobre'
    | '/voluntario'
    | '/admin/esqueci-senha'
    | '/admin/login'
    | '/admin/redefinir-senha'
    | '/agenda/$slug'
    | '/mensagens/$slug'
    | '/p/$slug'
    | '/agenda/'
    | '/mensagens/'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/eventos'
    | '/_authenticated/admin/formularios'
    | '/_authenticated/admin/mensagens'
    | '/_authenticated/admin/paginas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  DoacaoRoute: typeof DoacaoRoute
  MinisteriosRoute: typeof MinisteriosRoute
  OndeEstamosRoute: typeof OndeEstamosRoute
  RedesRoute: typeof RedesRoute
  SobreRoute: typeof SobreRoute
  VoluntarioRoute: typeof VoluntarioRoute
  AdminEsqueciSenhaRoute: typeof AdminEsqueciSenhaRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRedefinirSenhaRoute: typeof AdminRedefinirSenhaRoute
  AgendaSlugRoute: typeof AgendaSlugRoute
  MensagensSlugRoute: typeof MensagensSlugRoute
  PSlugRoute: typeof PSlugRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
  MensagensIndexRoute: typeof MensagensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doacao': {
      id: '/doacao'
      path: '/doacao'
      fullPath: '/doacao'
      preLoaderRoute: typeof DoacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministerios': {
      id: '/ministerios'
      path: '/ministerios'
      fullPath: '/ministerios'
      preLoaderRoute: typeof MinisteriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onde-estamos': {
      id: '/onde-estamos'
      path: '/onde-estamos'
      fullPath: '/onde-estamos'
      preLoaderRoute: typeof OndeEstamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redes': {
      id: '/redes'
      path: '/redes'
      fullPath: '/redes'
      preLoaderRoute: typeof RedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voluntario': {
      id: '/voluntario'
      path: '/voluntario'
      fullPath: '/voluntario'
      preLoaderRoute: typeof VoluntarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/esqueci-senha': {
      id: '/admin/esqueci-senha'
      path: '/admin/esqueci-senha'
      fullPath: '/admin/esqueci-senha'
      preLoaderRoute: typeof AdminEsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/redefinir-senha': {
      id: '/admin/redefinir-senha'
      path: '/admin/redefinir-senha'
      fullPath: '/admin/redefinir-senha'
      preLoaderRoute: typeof AdminRedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$slug': {
      id: '/agenda/$slug'
      path: '/agenda/$slug'
      fullPath: '/agenda/$slug'
      preLoaderRoute: typeof AgendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/': {
      id: '/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof MensagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensagens/$slug': {
      id: '/mensagens/$slug'
      path: '/mensagens/$slug'
      fullPath: '/mensagens/$slug'
      preLoaderRoute: typeof MensagensSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/formularios': {
      id: '/_authenticated/admin/formularios'
      path: '/admin/formularios'
      fullPath: '/admin/formularios'
      preLoaderRoute: typeof AuthenticatedAdminFormulariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mensagens': {
      id: '/_authenticated/admin/mensagens'
      path: '/admin/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AuthenticatedAdminMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/paginas': {
      id: '/_authenticated/admin/paginas'
      path: '/admin/paginas'
      fullPath: '/admin/paginas'
      preLoaderRoute: typeof AuthenticatedAdminPaginasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
  AuthenticatedAdminFormulariosRoute: typeof AuthenticatedAdminFormulariosRoute
  AuthenticatedAdminMensagensRoute: typeof AuthenticatedAdminMensagensRoute
  AuthenticatedAdminPaginasRoute: typeof AuthenticatedAdminPaginasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
  AuthenticatedAdminFormulariosRoute: AuthenticatedAdminFormulariosRoute,
  AuthenticatedAdminMensagensRoute: AuthenticatedAdminMensagensRoute,
  AuthenticatedAdminPaginasRoute: AuthenticatedAdminPaginasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ContatoRoute: ContatoRoute,
  DoacaoRoute: DoacaoRoute,
  MinisteriosRoute: MinisteriosRoute,
  OndeEstamosRoute: OndeEstamosRoute,
  RedesRoute: RedesRoute,
  SobreRoute: SobreRoute,
  VoluntarioRoute: VoluntarioRoute,
  AdminEsqueciSenhaRoute: AdminEsqueciSenhaRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRedefinirSenhaRoute: AdminRedefinirSenhaRoute,
  AgendaSlugRoute: AgendaSlugRoute,
  MensagensSlugRoute: MensagensSlugRoute,
  PSlugRoute: PSlugRoute,
  AgendaIndexRoute: AgendaIndexRoute,
  MensagensIndexRoute: MensagensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
